# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
# Show full path
truncation_length = 0

[cmd_duration]
disabled = true

[git_status]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[perl]
disabled = true

[python]
disabled = false
