# Reusable snippets ("macros") for other parts of the configuration
macros:
  default_ctx: 65536
  max_predict: 32768

  default_params: |
    --port ${PORT}
    --no-context-shift

  # https://medium.com/@michael.hannecke/tuning-llama-cpp-on-apple-silicon-843f37a6c3dc
  macos_optimal_params: |
    --batch-size 2048
    --ubatch-size 2048
    --mlock
    --prio 2

  qwen_params: |
    ${macos_optimal_params}
    --ctx-size ${default_ctx} 
    --predict ${max_predict} 
    --n-gpu-layers 99
    --temp 0.6 
    --top-p 0.95 
    --top-k 20 
    --repeat-penalty 1.00 
    --presence-penalty 0.00 
    --fit on 
    --flash-attn on 
    --cache-type-k q8_0
    --cache-type-v q8_0
    --chat-template-kwargs '{"preserve_thinking": true}'

models:
  unsloth-qwen3.6-35b-a3b:
    cmd: |
      llama-server 
        -hf "unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_M"
        ${default_params}
        ${qwen_params}

  unsloth-qwen3.6-27b:
    cmd: |
      llama-server 
        -hf "unsloth/Qwen3.6-27B-GGUF:UD-Q4_K_XL"
        ${default_params}
        ${qwen_params}

  unsloth-qwen3.8-27b:
    cmd: |
      llama-server
        -hf "unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL"
        ${default_params}
        ${qwen_params}
        --chat-template-kwargs '{"preserve_thinking": true, "reasoning_effort": "high"}'

  unsloth-gemma-4-12b-it-qat:
    cmd: |
      llama-server 
        -hf "unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL"
        ${default_params}
        --ctx-size ${default_ctx} 
        --predict ${max_predict} 
        --spec-type draft-mtp 
        --spec-draft-n-max 4

  smollm2-1.7b-instruct:
    cmd: |
      llama-server 
      -hf "HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF"
        ${default_params}
        --ctx-size 8192
        --predict 2048
