#!/usr/bin/env python3

import argparse
import re
import subprocess


ip_re = re.compile(r"^\d+.\d+.\d+.\d+$")


def run_for_ip(ip):
    output = subprocess.check_output(["curl", "-s", f"https://ipinfo.io/{ip}"])
    print(output.decode("utf-8"))


def run_for_domain(domain):
    output = subprocess.check_output(["dig", "+short", domain])
    addrs = output.decode("utf-8").splitlines()

    for ip in addrs:
        run_for_ip(ip)


def run():
    parser = argparse.ArgumentParser()
    parser.add_argument("host", type=str, help="IP or domain to check")
    args = parser.parse_args()

    input = args.host
    if ip_re.match(input):
        run_for_ip(input)
    else:
        run_for_domain(input)


if __name__ == "__main__":
    run()
