#!/bin/bash

        RED="\[\033[0;31m\]"
     YELLOW="\[\033[1;33m\]"
      GREEN="\[\033[0;32m\]"
       BLUE="\[\033[1;34m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\e[0m\]"

function is_git_repository {
  git branch > /dev/null 2>&1
}

function set_git_branch {
  branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"
  BRANCH="${GREEN}(${branch})${COLOR_NONE} "
}

function set_virtualenv () {
  if test -z "$VIRTUAL_ENV" ; then
      PYTHON_VIRTUALENV=""
  else
      PYTHON_VIRTUALENV="${BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
  fi
}

function set_bash_prompt () {
  PROMPT_SYMBOL="\$"

  set_virtualenv

  if is_git_repository ; then
    set_git_branch
  else
    BRANCH=''
  fi

  PS1="\n${GREEN}\u ${YELLOW}\w${COLOR_NONE} ${BRANCH}${PYTHON_VIRTUALENV} \n${PROMPT_SYMBOL} "
}

PROMPT_COMMAND=set_bash_prompt
